---
- name: Copy agent executable
  copy:
    src: "./agent/agent"
    dest: "{{ home }}/agent"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Copy chain map
  copy:
    src: "./map.json"
    dest: "{{ home }}/map.json"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Fetch core count
  shell: "cat /proc/cpuinfo | grep processor | wc -l"
  register: core_count

- name: Fetch address from key file
  shell: "grep -oP '(?<=\"address\":\")[^\"]*' {{ home }}/.local/share/io.parity.ethereum/keys/{{ genesis_network_name }}/peer.key"
  when: inventory_hostname in groups['peer']
  register: address

- name: Copy config json
  template:
    src: "config.json.j2"
    dest: "{{ home }}/config.json"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: install poa-agent service
  become: true
  template: src=poa-agent.service.j2 dest=/etc/systemd/system/poa-agent.service owner=root group=root mode=0755

- name: ensure poa-agemt is running and enabled to start at boot
  become: true
  service: name=poa-agent.service state=restarted enabled=yes daemon_reload=yes
