- name: Configure agent
  hosts: all
  gather_facts: no
  remote_user: root
  tasks:
    - name: Uninstall parity
      apt:
        name: parity
        state: absent

    - name: Install new version of parity
      apt:
        deb: "{{ parity_deb }}"

    - name: Restart parity
      service: name=parity.service state=restarted