#- name: Update bootnodes
#  hosts: all
#  gather_facts: no
#  remote_user: ubuntu
#  tasks:
#    - name: Fetch enode address string
#      shell: "grep -oP '(?<=Public node URL: ).*' {{ home}}/logs/parity.log"
#      register: enode
#
#    - name: Remove bootnodes.txt
#      file:
#        state: absent
#        path: ./bootnodes.txt
#      delegate_to: localhost
#
#    - name: Save enode address
#      lineinfile:
#        path: ./bootnodes.txt
#        line: "{{ enode.stdout }}"
#        create: yes
#      delegate_to: localhost
#
#    - name: Replace bootnodes.txt at all hosts
#      copy:
#        src: ./bootnodes.txt
#        dest: "{{ home }}/bootnodes.txt"
#        owner: "{{ username }}"
#        group: "{{ username }}"
#        mode: 0644
#
#    - name: Restart parity
#      become: true
#      service: name=parity.service state=restarted

- name: Parity
  hosts: all
  gather_facts: no
  remote_user: ubuntu
  become: true
  tasks:
    - name: Restart parity
      service: name=parity.service state=restarted

- name: Agent
  hosts: peer
  gather_facts: no
  remote_user: ubuntu
  become: true
  tasks:
    - name: Restart poa-agent
      service: name=poa-agent.service state=restarted