---
- name: 'Install python2'
  raw: sudo apt-get -y install python-simplejson

- name: Collect CPU info
  shell: "lscpu | sed -nr '/Model name/ s/.*:\\s*(.* @ .*)/\\1/p'"
  register: cpu_info

- name: Write CPU info
  lineinfile:
    path: ./tmp/latest/cpuinfo.txt
    line: "{{ name }}: {{ cpu_info.stdout }}"
    create: yes
  delegate_to: localhost

- name: Upgrade packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600

- name: Install ntpdate
  become: true
  apt:
    name:
      - ntpdate

- name: Stop NTP server
  become: true
  service: name=ntp state=stopped

- name: Sync time with ntp server
  become: true
  shell: "ntpdate 0.nl.pool.ntp.org"

- name: Start NTP server
  become: true
  service: name=ntp state=started
