---
- name: 'Install python2'
  raw: sudo apt-get -y install python-simplejson

- name: Upgrade packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600

- name: Install ntpdate
  apt:
    name:
      - ntpdate

- name: Sync time with ntp server
  shell: "ntpdate 0.nl.pool.ntp.org"

- name: Create new user
  user:
    name: ubuntu
    shell: /bin/bash

- name: Create .ssh folder
  file:
    path: ~ubuntu/.ssh
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0700

- name: Upload SSH key
  copy:
    src: ~/.ssh/do.pub
    dest: ~ubuntu/.ssh/authorized_keys
    owner: ubuntu
    group: ubuntu
    mode: 0700
