- hosts: localhost
  gather_facts: yes
  tasks:
    - name: ensure key exists at DigitalOcean
      digital_ocean: >
        state=present
        command=ssh
        name="aura experiment key"
        ssh_pub_key={{ lookup('file', '~/.ssh/do.pub') }}
      register: my_ssh_key

    - digital_ocean: >
        name={{ item }}
        state=present
        command=droplet
        unique_name=yes
        size_id={{ do_size }}
        region_id={{ do_region }}
        image_id={{ do_image_id }}
        ssh_key_ids={{ my_ssh_key.ssh_key.id }}
      with_sequence: start=0 end={{ peers_count - 1 }} format=peer-%d
      register: droplet_details

    - debug:
        msg: "IP is {{ item.droplet.ip_address }}"
      with_items: "{{ droplet_details.results }}"

    - name: remove hosts.txt
      file:
        state: absent
        path: ./hosts.txt

    - name: create new hosts.txt
      lineinfile:
        path: ./hosts.txt
        line: "[peer]"
        create: yes

    - name: add dropet IPs to hosts.txt
      lineinfile:
        path: ./hosts.txt
        line: "{{ item.droplet.ip_address }} name={{ item.droplet.name }} type=peer"
      with_items: "{{ droplet_details.results }}"

    - debug:
        msg: "IP: {{ item.droplet.ip_address }}, ID: {{ item.droplet.id }}"
      with_items: "{{ droplet_details.results }}"

    - digital_ocean_tag:
        name: "tn-{{ timestamp}}"
        resource_id: "{{ item.droplet.id }}"
        state: present
      with_items: "{{ droplet_details.results }}"

    - digital_ocean: >
        name={{ item }}
        state=present
        command=droplet
        unique_name=yes
        size_id={{ do_size }}
        region_id={{ do_region }}
        image_id={{ do_image_id }}
        ssh_key_ids={{ my_ssh_key.ssh_key.id }}
      with_sequence: start=0 end={{ validators_count - 1 }} format=validator-%d
      register: droplet_details

    - debug:
        msg: "IP is {{ item.droplet.ip_address }}"
      with_items: "{{ droplet_details.results }}"

    - name: create new hosts.txt
      lineinfile:
        path: ./hosts.txt
        line: "\n[validator]"

    - name: add dropet IPs to hosts.txt
      lineinfile:
        path: ./hosts.txt
        line: "{{ item.droplet.ip_address }} name={{ item.droplet.name }} type=validator"
      with_items: "{{ droplet_details.results }}"

    - debug:
        msg: "IP: {{ item.droplet.ip_address }}, ID: {{ item.droplet.id }}"
      with_items: "{{ droplet_details.results }}"

    - digital_ocean_tag:
        name: "tn-{{ timestamp}}"
        resource_id: "{{ item.droplet.id }}"
        state: present
      with_items: "{{ droplet_details.results }}"