---
- name: Upgrade packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Install collectd
  apt:
    name:
      - collectd
      - collectd-utils

- name: Install statsd
  apt:
    deb: https://kenig-public.ams3.digitaloceanspaces.com/statsd_0.8.0-1_all.deb

- name: Configure collectd
  template:
    src: "collectd.conf"
    dest: /etc/collectd/collectd.conf
    owner: root
    group: root
    mode: 0644

- name: Configure statsd
  template:
    src: "localConfig.js"
    dest: /etc/statsd/localConfig.js
    owner: root
    group: root
    mode: 0644

- name: Restart statsd
  service: name=collectd state=restarted

- name: Restarting statsd
  service: name=statsd state=restarted