---
- name: Install parity
  become: true
  apt:
    deb: "{{ parity_deb }}"

- name: install parity service
  become: true
  template: src=parity.service.j2 dest=/etc/systemd/system/parity.service owner=root group=root mode=0755

- name: ensure parity is running and enabled to start at boot
  become: true
  service: name=parity.service state=started enabled=yes

- name: Sleep for 30 seconds until enode uppear in logs
  wait_for: timeout=30
  delegate_to: localhost

- name: Fetch enode address string
  shell: "grep -oP '(?<=Public node URL: ).*' {{ home}}/logs/parity.log"
  register: enode

- name: Remove bootnodes.txt
  file:
    state: absent
    path: ./bootnodes.txt
  delegate_to: localhost

- name: Save enode address
  lineinfile:
    path: ./bootnodes.txt
    line: "{{ enode.stdout }}"
    create: yes
  delegate_to: localhost

- name: Replace bootnodes.txt at all hosts
  copy:
    src: ./bootnodes.txt
    dest: "{{ home }}/bootnodes.txt"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Restart parity
  become: true
  service: name=parity.service state=restarted